### ISSUE TITLE
Page crashes on load

### ISSUE THREAD

**Issue by nostrangerdev** [arkin0x/crashglow#1]
The site seems to crash after a moment since the page load.

Upon a quick inspection the issue seems to be from the function `isTest` in `src/components/Home.tsx`.

**Comment by arkin0x** [comment]
Thank you @nostrangerdev ! I fixed it with a slew of dumb commits tonight. Should be working now! https://github.com/arkin0x/crashglow/commit/1357c2b47eb06f796fc3e6ec8de4fac020a0d0b7

**Comment by nostrangerdev** [comment]
Fantastic!

Thank you for building it. 😎
